[project]
name = "custom-mcp"
version = "0.1.0"
description = "Common Tools Model Context Protocol (MCP) server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.4.1",
    "pytz>=2025.2",
]
